# Generated by Django 3.0.7 on 2021-01-15 13:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fullname', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=254)),
                ('age', models.IntegerField(default=0)),
                ('personal_contact', models.IntegerField()),
                ('relative_contact', models.IntegerField()),
                ('friends_contact', models.IntegerField()),
                ('address', models.TextField(max_length=1000)),
                ('image', models.ImageField(default='default.jpg', upload_to='profile_pics/')),
                ('blood_group', models.CharField(max_length=50)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Medical_Record',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_time', models.DateTimeField(default=django.utils.timezone.now)),
                ('title', models.CharField(max_length=200)),
                ('desciption', models.TextField(max_length=500)),
                ('hospital_name', models.CharField(max_length=200)),
                ('report', models.ImageField(default='default.jpg', upload_to='profile_pics/')),
                ('clinet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='detection.Client')),
            ],
        ),
    ]
