# Generated by Django 3.0.7 on 2021-01-15 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('detection', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medical_record',
            name='report',
            field=models.ImageField(default='default.jpg', upload_to='change/profile_pics/'),
        ),
    ]
