# Generated by Django 3.0.7 on 2021-01-15 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('detection', '0002_auto_20210115_1343'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medical_record',
            name='report',
            field=models.ImageField(default='default.jpg', upload_to='profile_pics/'),
        ),
    ]
