# Generated by Django 3.0.7 on 2021-01-15 13:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('detection', '0003_auto_20210115_1344'),
    ]

    operations = [
        migrations.RenameField(
            model_name='medical_record',
            old_name='clinet',
            new_name='client',
        ),
    ]
