# Generated by Django 3.0.7 on 2021-01-23 20:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('detection', '0005_auto_20210115_1350'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='client',
            name='friends_contact',
        ),
    ]
