# Generated by Django 3.0.7 on 2021-01-27 20:07

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('detection', '0006_remove_client_friends_contact'),
    ]

    operations = [
        migrations.RenameField(
            model_name='medical_record',
            old_name='desciption',
            new_name='description',
        ),
        migrations.RemoveField(
            model_name='medical_record',
            name='date_time',
        ),
        migrations.AddField(
            model_name='medical_record',
            name='amount',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='medical_record',
            name='date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
