# Generated by Django 3.0.7 on 2021-01-27 20:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('detection', '0007_auto_20210127_2007'),
    ]

    operations = [
        migrations.RenameField(
            model_name='medical_record',
            old_name='report',
            new_name='image',
        ),
    ]
