# Generated by Django 3.0.7 on 2021-01-28 08:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('detection', '0008_auto_20210127_2043'),
    ]

    operations = [
        migrations.RenameField(
            model_name='medical_record',
            old_name='hospital_name',
            new_name='hospital',
        ),
    ]
